auth:
  secret: ${auth-secret}
logging:
  level:
    root: info
    help.ukraine.app: info
server:
  error:
    include-message: always
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;
    username: SA
    password:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  cloud:
    gcp:
      sql:
        enabled: false
  mail:
    host: smtp.office365.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

