auth:
  secret: ${auth-secret}
logging:
  level:
    root: info
    help.ukraine.app: info
server:
  error:
    include-message: always
spring:
  sql:
    init:
      mode: never
  datasource:
    username: ${db-user}
    password: ${db-pwd}
    platform: postgres
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
  cloud:
    gcp:
      sql:
        enabled: true
        database-name: ${db-name}
        instance-connection-name: ${db-connection}
  mail:
    host: 142.251.1.108
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

