auth:
  secret: ${auth-secret}
logging:
  level:
    root: info
    help.ukraine.app: info
server:
  error:
    include-message: always
spring:
  sql:
    init:
      mode: never
  datasource:
    username: ${db-user}
    password: ${db-pwd}
    platform: postgres
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
  cloud:
    gcp:
      sql:
        enabled: true
        database-name: ${db-name}
        instance-connection-name: ${db-connection}
  mail:
    host: smpt.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      smpt:
        auth: true
        starttls:
          enable: true

